
const STATUS_COLORS={Pendente:'#f39c12','Em Producao':'#4a90e2',Concluido:'#2ecc71',Retirado:'#95a5a6',Cancelado:'var(--red)'};
const DONUT_ORDER=['Pendente','Em Producao','Concluido','Retirado'];
const ACTIVE_STATUSES=['Pendente','Em Producao'];
const STEPS=['Pendente','Em Producao','Concluido','Retirado'];
const API_URL='api.php';
const TOKEN_KEY='octoview_token';
const THEME_KEY='octoview_theme';
const UNIT_FILTER_KEY='octoview_unit_filter';
const MOBILE_BREAKPOINT=768;
let currentUser=null,editingFilamentId=null,editingModelId=null,editingStatusOrderId=null,galleryOrderModelId=null,viewingOrderId=null;
let filaments=[],models=[],orders=[],history=[],users=[],sectors=[],units=[],usersById={},selectedUnitId='',filamentStats={totals:{registered:0,active:0},byUnit:[]},consumptionStats={totals:{totalWeight:0,rolls:0},byUnit:[]},dashboardStatusFilter='';
let pendingProfilePhotoRemoval=false;
let selectedProfilePhotoFile=null;
let selectedProfilePhotoUrl='';

window.addEventListener('load',async()=>{
  applyStoredTheme();
  document.getElementById('tb-date').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'});
  document.querySelectorAll('.mo').forEach(modal=>modal.addEventListener('click',event=>{if(event.target===modal)closeM(modal.id);}));
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){const modal=document.querySelector('.mo.on');if(modal)closeM(modal.id);if(document.getElementById('app')?.classList.contains('menu-open'))closeMobileMenu();}});
  window.addEventListener('resize',syncMobileMenuState);
  setTimeout(()=>document.getElementById('ld').classList.add('off'),1200);
  if(!getToken())return;
  try{await loadBootstrap();openApp();}catch(error){clearToken();toast(error.message||'Sua sessao expirou.','e');}
});

function getToken(){return localStorage.getItem(TOKEN_KEY)||'';}
function setToken(token){localStorage.setItem(TOKEN_KEY,token);}
function clearToken(){localStorage.removeItem(TOKEN_KEY);}
function applyStoredTheme(){const stored=localStorage.getItem(THEME_KEY);const theme=stored||(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.documentElement.setAttribute('data-theme',theme);syncThemeButtons(theme);}
function toggleTheme(){const current=document.documentElement.getAttribute('data-theme')==='dark'?'dark':'light';const next=current==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',next);localStorage.setItem(THEME_KEY,next);syncThemeButtons(next);}
function syncThemeButtons(theme){document.querySelectorAll('.theme-toggle').forEach(button=>{const label=theme==='dark'?'Ativar tema claro':'Ativar tema escuro';button.setAttribute('aria-pressed',String(theme==='dark'));button.setAttribute('aria-label',label);button.setAttribute('title',label);if(!button.classList.contains('theme-toggle-icon'))button.textContent=theme==='dark'?'Tema claro':'Tema escuro';});}
function toggleLoginPassword(){const input=document.getElementById('login-pass');const button=document.querySelector('.login-password-toggle');if(!input||!button)return;const reveal=input.type==='password';input.type=reveal?'text':'password';button.setAttribute('aria-label',reveal?'Ocultar senha':'Mostrar senha');button.setAttribute('aria-pressed',String(reveal));}

async function doLogin(event){
  if(event)event.preventDefault();
  const usuario=document.getElementById('login-user').value.trim();
  const senha=document.getElementById('login-pass').value;
  if(!usuario||!senha){toast('Informe usuario e senha.','e');return;}
  const submitButton=document.querySelector('.login-form .lbtn');
  const originalLabel=submitButton?.textContent||'Entrar no sistema';
  try{
    if(submitButton){submitButton.disabled=true;submitButton.classList.add('is-loading');submitButton.textContent='Entrando...';}
    const payload=await apiRequest('login','POST',{usuario,senha},false);
    setToken(payload.token);
    if(payload.senhaTemporaria){
      toast('Sua senha atual e temporaria (1234).','i');
      await maybeChangeTemporaryPassword(senha);
    }
    await loadBootstrap();
    openApp();
    document.getElementById('login-pass').value='';
    toast(`Bem-vindo(a), ${currentUser.nm}!`,'s');
  }catch(error){toast(error.message||'Falha no login.','e');}
  finally{if(submitButton){submitButton.disabled=false;submitButton.classList.remove('is-loading');submitButton.textContent=originalLabel;}}
}

function doLogout(){
  clearToken();localStorage.removeItem(UNIT_FILTER_KEY);currentUser=null;editingFilamentId=null;editingModelId=null;editingStatusOrderId=null;galleryOrderModelId=null;viewingOrderId=null;selectedUnitId='';
  closeMobileMenu();
  document.getElementById('app').style.display='none';document.getElementById('app').setAttribute('aria-hidden','true');document.getElementById('app').classList.remove('on');
  document.getElementById('lsc').classList.remove('off');document.getElementById('login-user').value='';document.getElementById('login-pass').value='';document.querySelectorAll('.sec').forEach(section=>section.classList.remove('on'));
  const toggleButton=document.querySelector('.login-password-toggle');if(toggleButton){toggleButton.setAttribute('aria-label','Mostrar senha');toggleButton.setAttribute('aria-pressed','false');}
  document.getElementById('login-pass').type='password';
}

async function submitForgotPassword(){
  const identificador=window.prompt('Informe o usuario, email ou matricula para redefinir a senha:','');
  if(identificador===null)return;
  const valor=identificador.trim();
  if(!valor){toast('Informe usuario, email ou matricula.','e');return;}
  const confirmed=window.confirm(`Confirmar redefinicao da senha do usuario informado para 1234?`);
  if(!confirmed)return;
  try{const payload=await apiRequest('forgot-password','POST',{identificador:valor},false);document.getElementById('login-user').value=payload.usuario||valor;document.getElementById('login-pass').value='1234';toast(`Senha redefinida para 1234 para o usuario ${payload.usuario}.`,'s');}catch(error){toast(error.message||'Falha ao redefinir senha.','e');}
}

async function maybeChangeTemporaryPassword(senhaAtual){
  const confirmed=window.confirm('Deseja alterar sua senha agora?');
  if(!confirmed)return;
  const novaSenha=(window.prompt('Digite a nova senha (minimo 4 caracteres):','')||'').trim();
  if(novaSenha.length<4){toast('A nova senha precisa ter ao menos 4 caracteres.','e');return;}
  const confirmacao=(window.prompt('Confirme a nova senha:','')||'').trim();
  if(novaSenha!==confirmacao){toast('As senhas informadas nao conferem.','e');return;}
  await apiRequest('change-password','POST',{senhaAtual,novaSenha});
  toast('Senha alterada com sucesso.','s');
}

function openApp(){document.getElementById('lsc').classList.add('off');const app=document.getElementById('app');app.style.display='flex';app.setAttribute('aria-hidden','false');setTimeout(()=>app.classList.add('on'),10);setupSidebar();refreshAllSelects();syncMobileMenuState();go(isAdmin()?'dashboard':'galeria');document.getElementById('main-content').focus();}

async function loadBootstrap(){const payload=await apiRequest('bootstrap');ingestBootstrap(payload);if(!currentUser)throw new Error('Sessao invalida.');}
function ingestBootstrap(payload){filaments=payload.filaments||[];models=payload.models||[];orders=payload.orders||[];history=payload.history||[];users=payload.users||[];sectors=payload.sectors||[];units=payload.units||[];filamentStats=payload.filamentStats||{totals:{registered:0,active:0},byUnit:[]};consumptionStats=payload.consumptionStats||{totals:{totalWeight:0,rolls:0},byUnit:[]};currentUser=payload.currentUser||currentUser;usersById=Object.fromEntries(users.map(user=>[user.id,user]));syncSelectedUnit();refreshAllSelects();}

function getSidebarDisplayName(name){const parts=String(name||'').trim().split(/\s+/).filter(Boolean);if(parts.length<=1)return parts[0]||'';return `${parts[0]} ${parts[parts.length-1]}`;}

function setupSidebar(){
  document.getElementById('sb-av').innerHTML=currentUser.foto?`<img src="${currentUser.foto}" alt="Foto de ${escapeHtml(currentUser.nm)}">`:escapeHtml(currentUser.nm.charAt(0).toUpperCase());
  document.getElementById('sb-nm').textContent=getSidebarDisplayName(currentUser.nm);document.getElementById('tb-userline').textContent=`${currentUser.usuario} · ${currentUser.setor}`;
  const role=document.getElementById('sb-role');role.textContent=currentUser.tipo==='admin'?'Admin':'Solicitante';role.className=`rpill ${currentUser.tipo==='admin'?'admin':'comum'}`;
  document.querySelectorAll('.adm').forEach(element=>{element.style.display=isAdmin()?(element.classList.contains('nav-sec')?'block':'flex'):'none';});
  document.querySelectorAll('.national-only').forEach(element=>{element.style.display=isNationalAdmin()?'flex':'none';});
  document.querySelectorAll('.admin-only,.admin-only-inline').forEach(el=>{el.style.display=isAdmin()?'inline-flex':'none';});const filterWrap=document.getElementById('tb-unit-wrap');if(filterWrap)filterWrap.style.display=isNationalAdmin()?'inline-flex':'none';const queueSubtitle=document.getElementById('queue-subtitle');if(queueSubtitle)queueSubtitle.textContent=isAdmin()?'Gerencie e acompanhe a fila da unidade visivel':'Acompanhe a fila de impressao da sua unidade';configureUserFormAccess();
}

function go(section){
  if(!currentUser)return;const adminSections=['dashboard','estoque','galeria-admin','usuarios','unidades'];if(!isAdmin()&&adminSections.includes(section))section='galeria';if(section==='unidades'&&!isNationalAdmin())section='usuarios';
  document.querySelectorAll('.ni').forEach(item=>item.classList.remove('on'));const nav=document.querySelector(`.ni[data-section="${section}"]`);if(nav)nav.classList.add('on');
  document.querySelectorAll('.sec').forEach(item=>item.classList.remove('on'));const target=document.getElementById(`sec-${section}`);if(target)target.classList.add('on');
  document.getElementById('tb-t').textContent={dashboard:'Visao Geral','pedidos-admin':'Fila de Pedidos',estoque:'Estoque de Filamentos','galeria-admin':'Galeria - Gestao',usuarios:'Usuarios',unidades:'Unidades',galeria:'Galeria de Modelos','novo-pedido':'Novo Pedido','meus-pedidos':'Meus Pedidos'}[section]||section;
  refreshAllSelects();
  if(section==='dashboard')renderDashboard();
  if(section==='pedidos-admin')renderOrdersAdmin();
  if(section==='estoque')renderStock();
  if(section==='galeria-admin')renderGalleryAdmin();
  if(section==='usuarios')renderUsersAdmin();
  if(section==='unidades')renderUnitsAdmin();
  if(section==='galeria')renderGalleryPublic(document.getElementById('src-g')?.value||'');
  if(section==='novo-pedido')renderNewOrderContext();
  if(section==='meus-pedidos')renderMyOrders();
  if(isMobileViewport())closeMobileMenu();
}

function isMobileViewport(){return window.matchMedia(`(max-width:${MOBILE_BREAKPOINT}px)`).matches;}
function toggleMobileMenu(forceOpen=null){
  const app=document.getElementById('app');if(!app)return;
  if(!isMobileViewport()){closeMobileMenu();return;}
  const nextState=typeof forceOpen==='boolean'?forceOpen:!app.classList.contains('menu-open');
  app.classList.toggle('menu-open',nextState);
  document.body.classList.toggle('menu-open-body',nextState);
  const toggleButton=document.getElementById('menu-toggle');if(toggleButton){toggleButton.setAttribute('aria-expanded',String(nextState));toggleButton.setAttribute('aria-label',nextState?'Fechar menu de navegacao':'Abrir menu de navegacao');}
}
function closeMobileMenu(){
  const app=document.getElementById('app');if(!app)return;
  app.classList.remove('menu-open');
  document.body.classList.remove('menu-open-body');
  const toggleButton=document.getElementById('menu-toggle');if(toggleButton){toggleButton.setAttribute('aria-expanded','false');toggleButton.setAttribute('aria-label','Abrir menu de navegacao');}
}
function syncMobileMenuState(){if(!isMobileViewport())closeMobileMenu();}

function refreshAllSelects(){populateModelSelects();populateFilamentSelectsClean();populateSectorFilter();populateCreateUserSectors();populateUnitFilters();configureUserFormAccess();}
function populateFilamentSelectsClean(){const visibleFilaments=getVisibleFilaments();const options=visibleFilaments.map(filament=>`<option value="${filament.id}">${escapeHtml(filament.cor)} · ${escapeHtml(filament.tipo)}</option>`).join('');['np-fil','gal-fil'].forEach(id=>{const select=document.getElementById(id);if(!select)return;const current=select.value;select.innerHTML=options;if(current&&visibleFilaments.some(f=>String(f.id)===current))select.value=current;else if(visibleFilaments[0])select.value=String(visibleFilaments[0].id);});}
function populateModelSelects(){const select=document.getElementById('np-mod');if(!select)return;const current=select.value;select.innerHTML=`<option value="">- Sem modelo (envio referencia)</option>${models.map(model=>`<option value="${model.id}">${escapeHtml(model.nm)}</option>`).join('')}`;if(current&&models.some(model=>String(model.id)===current))select.value=current;}
function populateFilamentSelects(){const visibleFilaments=getVisibleFilaments();const options=visibleFilaments.map(filament=>`<option value="${filament.id}">${escapeHtml(filament.cor)} · ${escapeHtml(filament.tipo)} (${formatNumber(filament.peso)}g)</option>`).join('');['np-fil','gal-fil'].forEach(id=>{const select=document.getElementById(id);if(!select)return;const current=select.value;select.innerHTML=options;if(current&&visibleFilaments.some(f=>String(f.id)===current))select.value=current;else if(visibleFilaments[0])select.value=String(visibleFilaments[0].id);});}
function populateSectorFilter(){const select=document.getElementById('flt-st');if(!select)return;const current=select.value;const sectorNames=[...new Set(getVisibleUsers().map(user=>user.setor))].sort((a,b)=>a.localeCompare(b,'pt-BR'));select.innerHTML=`<option value="">Todos setores</option>${sectorNames.map(sector=>`<option value="${escapeHtml(sector)}">${escapeHtml(sector)}</option>`).join('')}`;select.value=sectorNames.includes(current)?current:'';}
function populateCreateUserSectors(){const select=document.getElementById('cu-setor');if(!select)return;const current=select.value;select.innerHTML='<option value="">Selecione</option>'+sectors.map(sector=>`<option value="${sector.id}">${escapeHtml(sector.nome)} (prioridade ${sector.prioridade})</option>`).join('');if(current&&sectors.some(sector=>String(sector.id)===current))select.value=current;}
function populateUnitFilters(){const topSelect=document.getElementById('tb-unit-filter');if(topSelect){topSelect.innerHTML=`<option value="">Todas as unidades</option>${units.map(unit=>`<option value="${unit.id}">${escapeHtml(unit.nome)}</option>`).join('')}`;topSelect.value=selectedUnitId?String(selectedUnitId):'';}const formSelect=document.getElementById('cu-unit');if(formSelect){const current=formSelect.value;const available=getAssignableUnits();formSelect.innerHTML='<option value="">Selecione</option>'+available.map(unit=>`<option value="${unit.id}">${escapeHtml(unit.nome)}${unit.cidade?` - ${escapeHtml(unit.cidade)}`:''}</option>`).join('');const fallback=String(currentUser?.unitId||'');formSelect.value=available.some(unit=>String(unit.id)===current)?current:fallback;formSelect.disabled=!isNationalAdmin();}}

function renderDashboard(){if(isNationalAdmin()){renderNationalDashboard();return;}const visibleOrders=getVisibleOrders();const visibleFilaments=getVisibleFilaments();const visibleUsers=getVisibleUsers();const filamentRollSummary=getFilamentRollSummary(visibleFilaments);const statusSummary=getOrderStatusSummary(visibleOrders);const recent=visibleOrders.filter(order=>daysBetween(order.data,today())<=7);const totalConsumption=getVisibleConsumptionStats();document.getElementById('stat-pedidos').textContent=String(statusSummary.activeTotal);document.getElementById('stat-pedidos-det').textContent=recent.length?`+ ${recent.length} novos`:'Sem novos pedidos';renderDashboardStockCard(filamentRollSummary,visibleFilaments);document.getElementById('stat-concluidos').textContent=formatWeight(totalConsumption.totalWeight);document.getElementById('stat-concluidos-det').textContent=formatConsumedRolls(totalConsumption.rolls);document.getElementById('stat-solicitantes').textContent=String(visibleUsers.length);document.getElementById('stat-solicitantes-det').textContent=`${new Set(visibleUsers.map(user=>user.setor)).size} setores ativos`;renderPriorityQueuePreview();renderStatusDonut();renderInstructorChart();renderUnitMetricsChart();}
function getLowStockFilament(filamentList){const ordered=[...filamentList].sort((a,b)=>Number(a.peso||0)-Number(b.peso||0));const lowest=ordered[0];if(!lowest)return null;return getFilamentStockLevel(lowest).level!=='ok'?lowest:null;}
function renderDashboardStockCard(filamentRollSummary,filamentList){const lowStock=getLowStockFilament(filamentList);const stockValue=document.getElementById('stat-estoque');const stockDetail=document.getElementById('stat-estoque-det');const stockCard=document.getElementById('stock-stat-card');const alertBadge=document.getElementById('stock-stat-alert-badge');stockValue.textContent=String(filamentRollSummary.rolls);if(lowStock){stockDetail.textContent=`Atencao: Estoque de ${lowStock.cor} baixo`;stockDetail.classList.add('stock-stat-warning');stockCard.classList.add('stock-stat-card-alert');alertBadge.style.display='inline-flex';return;}stockDetail.textContent=`${formatNumber(filamentRollSummary.totalWeight)}g totais`;stockDetail.classList.remove('stock-stat-warning');stockCard.classList.remove('stock-stat-card-alert');alertBadge.style.display='none';}
function handleStockCardKeydown(event){if(event.key==='Enter'||event.key===' '){event.preventDefault();go('estoque');}}
function renderPriorityQueuePreview(){const container=document.getElementById('fila-prev');const sorted=[...getVisibleOrders()].sort((a,b)=>b.pri-a.pri||a.data.localeCompare(b.data)).slice(0,5);if(!sorted.length){container.innerHTML=emptyState('Nenhum pedido na fila no momento.');return;}container.innerHTML=sorted.map((order,index)=>`<div class="fr"><div class="fn">${index+1}</div><div class="fi"><div class="fm">${escapeHtml(order.sol)} - ${escapeHtml(order.mod)}</div><div class="fs">${escapeHtml(order.setor)} · ${escapeHtml(order.fil)}${order.unidade?` · ${escapeHtml(order.unidade)}`:''}</div></div>${priorityMarkup(order.pri)}<span class="badge ${statusClass(order.st)}">${escapeHtml(order.st)}</span></div>`).join('');}
function getFilamentRollSummary(filamentList){const totalWeight=filamentList.reduce((sum,filament)=>sum+Math.max(0,Number(filament.peso)||0),0);return{totalWeight,rolls:totalWeight>0?Math.ceil(totalWeight/1000):0};}
function getOrderStatusSummary(orderList){const counts=DONUT_ORDER.map(status=>({status,count:orderList.filter(order=>order.st===status).length}));const activeTotal=orderList.reduce((sum,order)=>sum+(ACTIVE_STATUSES.includes(order.st)?1:0),0);return{counts,activeTotal};}
function renderStatusDonut(){const statusSummary=getOrderStatusSummary(getVisibleOrders());const counts=statusSummary.counts;const total=counts.reduce((sum,item)=>sum+item.count,0);const circumference=2*Math.PI*40;let offset=0;const circles=counts.filter(item=>item.count>0).map(item=>{const dash=item.count/Math.max(total,1)*circumference;const markup=`<circle cx="54" cy="54" r="40" stroke="${STATUS_COLORS[item.status]}" stroke-width="12" stroke-dasharray="${dash} ${circumference-dash}" stroke-dashoffset="-${offset}"></circle>`;offset+=dash;return markup;}).join('');document.getElementById('donut-chart').innerHTML=`<svg width="108" height="108" viewBox="0 0 108 108"><circle cx="54" cy="54" r="40" stroke="var(--donut-track)" stroke-width="12"></circle>${circles}</svg>`;document.getElementById('donut-total').textContent=String(statusSummary.activeTotal);document.getElementById('status-legend').innerHTML=counts.map(item=>`<div class="li"><div class="ld2" style="background:${STATUS_COLORS[item.status]}"></div>${escapeHtml(item.status)}<span class="lc2">${item.count}</span></div>`).join('');}
function renderOrdersAdmin(list=null){const tbody=document.getElementById('tbp');const data=[...(list||getVisibleOrders())].sort((a,b)=>b.pri-a.pri||a.data.localeCompare(b.data));if(!data.length){tbody.innerHTML=`<tr><td colspan="9">${emptyState('Nenhum pedido encontrado.',true)}</td></tr>`;return;}tbody.innerHTML=data.map(order=>`<tr><td><b style="font-weight:600;color:var(--tx3);font-size:0.77rem">#${order.id}</b></td><td style="font-weight:500">${escapeHtml(order.sol)}</td><td style="color:var(--tx2)">${escapeHtml(order.setor)}</td><td>${escapeHtml(order.mod)}</td><td><span style="display:inline-flex;align-items:center;gap:5px"><span style="width:8px;height:8px;border-radius:50%;background:${filamentHex(order.fId)};box-shadow:0 0 0 2px rgba(0,0,0,0.07);flex-shrink:0"></span>${escapeHtml(order.fil)}</span></td><td>${priorityMarkup(order.pri)}</td><td><span class="badge ${statusClass(order.st)}">${escapeHtml(statusLabel(order.st))}</span></td><td style="color:var(--tx3);font-size:0.77rem">${formatDate(order.data)}</td><td><div class="table-actions"><button class="btn bxs bg2" type="button" onclick="openOrderViewModal(${order.id})">Ver</button><button class="btn bxs s admin-only-inline" type="button" onclick="openStatusModal(${order.id})">Status</button></div></td></tr>`).join('');}
function filtP(){const query=document.getElementById('src-p').value.toLowerCase();const status=document.getElementById('flt-s').value;const sector=document.getElementById('flt-st').value;renderOrdersAdmin(getVisibleOrders().filter(order=>{const matches=!query||order.sol.toLowerCase().includes(query)||order.mod.toLowerCase().includes(query)||String(order.id).includes(query)||order.fil.toLowerCase().includes(query);return matches&&(!status||order.st===status)&&(!sector||order.setor===sector);}));}
function getFilamentStockLevel(filament){const weight=Math.max(0,Number(filament?.peso)||0);const capacity=Math.max(weight,Number(filament?.capacidade)||1000);const percentage=Math.max(0,Math.min(100,weight/capacity*100));if(weight<200)return{level:'critical',weight,percentage,badge:'bcrit',label:'CRITICO',barClass:'is-critical'};if(weight<=500)return{level:'warning',weight,percentage,badge:'bbai',label:'ATENCAO',barClass:'is-low'};return{level:'ok',weight,percentage,badge:'bok',label:'OK',barClass:'is-ok'};}
function renderStock(){const grid=document.getElementById('fil-grid');const tbody=document.getElementById('tbh');const sortedFilaments=[...filaments].sort((a,b)=>{const levelOrder={critical:0,warning:1,ok:2};const levelDiff=levelOrder[getFilamentStockLevel(a).level]-levelOrder[getFilamentStockLevel(b).level];if(levelDiff!==0)return levelDiff;return Number(a.peso||0)-Number(b.peso||0);});grid.innerHTML=!sortedFilaments.length?emptyState('Nenhum filamento cadastrado.'):sortedFilaments.map(f=>{const stockLevel=getFilamentStockLevel(f);const colorToken=getFilamentColorToken(f);const actions=currentUser.tipo==='admin'?`<div class="fca"><button class="btn bxs e" type="button" onclick="openFilModal(${f.id})">Editar</button><button class="btn bxs d" type="button" onclick="deleteFilament(${f.id})">Remover</button></div>`:'';return `<div class="fc"><div class="fct"><div class="fcdn"><div class="fcd" style="background:${colorToken.background};border:${colorToken.border};"></div><div class="fcn">${escapeHtml(f.cor)}</div></div><span class="badge ${stockLevel.badge}">${stockLevel.label}</span></div><div class="fctp">${escapeHtml(f.tipo)}</div><div class="fct2"><div class="fcf ${stockLevel.barClass}" style="width:${stockLevel.percentage}%;"></div></div><div class="fcst"><span class="fcg">${formatNumber(f.peso)}g</span><span class="fcp">${stockLevel.percentage.toFixed(0)}%</span></div>${actions}</div>`;}).join('');tbody.innerHTML=!history.length?`<tr><td colspan="4">${emptyState('Nenhuma movimentacao registrada.',true)}</td></tr>`:[...history].sort((a,b)=>b.data.localeCompare(a.data)).map(item=>`<tr><td style="color:var(--tx3);font-size:0.77rem">${formatDate(item.data)}</td><td>${escapeHtml(item.fil)}</td><td><span class="badge ${item.tipo==='Entrada'?'bconc':'bpend'}">${escapeHtml(item.tipo)}</span></td><td style="font-weight:600">${formatNumber(item.qtd)}g</td></tr>`).join('');}
function renderGalleryAdmin(){const container=document.getElementById('gal-adm');if(!models.length){container.innerHTML=emptyState('Nenhum modelo cadastrado.');return;}container.innerHTML=models.map(model=>`<div class="gc"><div class="gi">${galleryImageMarkup(model.foto)}</div><div class="gb"><div class="gn">${escapeHtml(model.nm)}</div><div class="gd">${escapeHtml(model.desc||'Sem descricao cadastrada.')}</div><div class="gf"><div class="gw">~<b>${formatNumber(model.peso)}g</b></div><div style="display:flex;gap:5px"><button class="btn bxs e" type="button" onclick="openModModal(${model.id})">Editar</button><button class="btn bxs d" type="button" onclick="deleteModel(${model.id})">Remover</button></div></div></div></div>`).join('');}
function renderUsersAdmin(){const tbody=document.getElementById('tbu');if(!tbody)return;const ordered=[...getVisibleUsers()].sort((a,b)=>a.nm.localeCompare(b.nm,'pt-BR'));tbody.innerHTML=!ordered.length?`<tr><td colspan="9">${emptyState('Nenhum usuario cadastrado.',true)}</td></tr>`:ordered.map(user=>`<tr><td>${escapeHtml(user.nm)}</td><td>${escapeHtml(user.usuario||'-')}</td><td>${escapeHtml(user.matricula||'-')}</td><td>${escapeHtml(user.email||'-')}</td><td>${escapeHtml(user.unidade||'-')}</td><td>${escapeHtml(user.setor)}</td><td><span class="rpill ${user.tipo==='admin'?'admin':'comum'}">${escapeHtml(userRoleLabel(user.perfil))}</span></td><td><span class="badge ${user.ativo?'bconc':'bcan'}">${user.ativo?'Ativo':'Inativo'}</span></td><td><div class="table-actions"><button class="btn bxs e" type="button" onclick="openEditUser(${user.id})">Editar</button>${user.ativo?`<button class="btn bxs d" type="button" onclick="inactivateUser(${user.id})">Inativar</button>`:''}</div></td></tr>`).join('');}

function getDashboardOrdersByStatus(){const visibleOrders=getVisibleOrders();return dashboardStatusFilter?visibleOrders.filter(order=>order.st===dashboardStatusFilter):visibleOrders;}
function toggleDashboardStatusFilter(status){dashboardStatusFilter=dashboardStatusFilter===status?'':status;renderPriorityQueuePreview();renderStatusDonut();}
function clearDashboardStatusFilter(){if(!dashboardStatusFilter)return;dashboardStatusFilter='';renderPriorityQueuePreview();renderStatusDonut();}
function handleDashboardDonutKeydown(event,status){if(event.key==='Enter'||event.key===' '){event.preventDefault();toggleDashboardStatusFilter(status);}}
function renderPriorityQueuePreview(){const container=document.getElementById('fila-prev');const sorted=[...getDashboardOrdersByStatus()].sort((a,b)=>b.pri-a.pri||a.data.localeCompare(b.data)).slice(0,5);if(!sorted.length){container.innerHTML=emptyState(dashboardStatusFilter?`Nenhum pedido com status ${dashboardStatusFilter}.`:'Nenhum pedido na fila no momento.');return;}container.innerHTML=sorted.map((order,index)=>`<div class="fr"><div class="fn">${index+1}</div><div class="fi"><div class="fm">${escapeHtml(order.sol)} - ${escapeHtml(order.mod)}</div><div class="fs">${escapeHtml(order.setor)} Â· ${escapeHtml(order.fil)}${order.unidade?` Â· ${escapeHtml(order.unidade)}`:''}</div></div>${priorityMarkup(order.pri)}<span class="badge ${statusClass(order.st)}">${escapeHtml(order.st)}</span></div>`).join('');}
function renderStatusDonut(){const statusSummary=getOrderStatusSummary(getVisibleOrders());const counts=statusSummary.counts;const activeTotal=counts.reduce((sum,item)=>sum+((item.status==='Pendente'||item.status==='Em Producao')?item.count:0),0);const total=counts.reduce((sum,item)=>sum+item.count,0);const circumference=2*Math.PI*40;let offset=0;const circles=counts.filter(item=>item.count>0).map(item=>{const dash=item.count/Math.max(total,1)*circumference;const isActive=dashboardStatusFilter===item.status;const safeStatus=escapeHtml(item.status);const markup=`<circle class="donut-segment${isActive?' is-active':''}" cx="54" cy="54" r="40" stroke="${STATUS_COLORS[item.status]}" stroke-width="12" stroke-dasharray="${dash} ${circumference-dash}" stroke-dashoffset="-${offset}" tabindex="0" role="button" aria-label="Filtrar fila por ${escapeHtml(statusLabel(item.status))}" onclick="toggleDashboardStatusFilter('${safeStatus}')" onkeydown="handleDashboardDonutKeydown(event,'${safeStatus}')"></circle>`;offset+=dash;return markup;}).join('');document.getElementById('donut-chart').innerHTML=`<svg width="108" height="108" viewBox="0 0 108 108"><circle cx="54" cy="54" r="40" stroke="var(--donut-track)" stroke-width="12"></circle>${circles}</svg>`;document.getElementById('donut-total').textContent=String(activeTotal);document.getElementById('status-legend').innerHTML=counts.map(item=>`<button class="li status-filter-chip${dashboardStatusFilter===item.status?' is-active':''}" type="button" onclick="toggleDashboardStatusFilter('${escapeHtml(item.status)}')" aria-pressed="${dashboardStatusFilter===item.status?'true':'false'}"><div class="ld2" style="background:${STATUS_COLORS[item.status]}"></div><span>${escapeHtml(statusLabel(item.status))}</span><span class="lc2">${item.count}</span></button>`).join('');const clearButton=document.getElementById('dashboard-status-clear');if(clearButton){clearButton.style.display=dashboardStatusFilter?'inline-flex':'none';clearButton.textContent=dashboardStatusFilter?`Limpar: ${statusLabel(dashboardStatusFilter)}`:'Limpar filtro';}}
function renderPriorityQueuePreview(){const container=document.getElementById('fila-prev');const sorted=[...getDashboardOrdersByStatus()].sort((a,b)=>b.pri-a.pri||a.data.localeCompare(b.data));if(!sorted.length){container.innerHTML=emptyState(dashboardStatusFilter?`Nenhum pedido com status ${statusLabel(dashboardStatusFilter)}.`:'Nenhum pedido prioritário no momento.');return;}container.innerHTML=sorted.map((order,index)=>`<div class="fr"><div class="dashboard-queue-marker" style="background:${filamentHex(order.fId)}"></div><div class="fn">${index+1}</div><div class="fi"><div class="fm">${escapeHtml(order.sol)} - ${escapeHtml(order.mod)}</div><div class="fs">${escapeHtml(order.setor)} · ${escapeHtml(order.fil)}${order.unidade?` · ${escapeHtml(order.unidade)}`:''}</div></div><div class="fr-status-wrap">${priorityMarkup(order.pri)}<span class="badge ${statusClass(order.st)}">${escapeHtml(statusLabel(order.st))}</span></div></div>`).join('');}

async function submitUserCreate(event){event.preventDefault();if(!isAdmin()){toast('Somente administradores podem cadastrar usuarios.','e');return;}const id=Number.parseInt(document.getElementById('cu-id').value,10)||null;const nome=document.getElementById('cu-nome').value.trim();const usuario=document.getElementById('cu-usuario').value.trim();const matricula=document.getElementById('cu-matricula').value.trim();const email=document.getElementById('cu-email').value.trim();const setorId=Number.parseInt(document.getElementById('cu-setor').value,10);const perfil=document.getElementById('cu-perfil').value;const unitId=Number.parseInt(document.getElementById('cu-unit').value,10);const tipo=perfil.startsWith('admin')?'admin':'comum';if(!nome||!usuario||!matricula||!email||Number.isNaN(setorId)||Number.isNaN(unitId)){toast('Preencha todos os campos do cadastro.','e');return;}if(!isNationalAdmin()&&perfil==='admin_nacional'){toast('Apenas administradores nacionais podem criar outro administrador nacional.','e');return;}try{if(id){const payload=await apiRequest('user-update','POST',{id,nome,usuario,matricula,email,setorId,tipo,perfil,unitId});ingestBootstrap(payload);renderUsersAdmin();resetCreateUserForm();toast(`Usuario ${usuario} atualizado com sucesso.`,'s');return;}const payload=await apiRequest('user-create','POST',{nome,usuario,matricula,email,setorId,tipo,perfil,unitId});ingestBootstrap(payload.bootstrap);resetCreateUserForm();renderUsersAdmin();toast(`Usuario ${payload.created.usuario} criado. Senha inicial: ${payload.created.senhaPadrao}`,'s');}catch(error){toast(error.message||'Falha ao cadastrar usuario.','e');}}
function resetCreateUserForm(){['cu-id','cu-nome','cu-usuario','cu-matricula','cu-email'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});document.getElementById('cu-setor').value='';document.getElementById('cu-perfil').value='colaborador';populateUnitFilters();document.getElementById('cu-submit').textContent='Cadastrar usuario';}
function openEditUser(id){const user=usersById[id];if(!user){toast('Usuario nao encontrado.','e');return;}document.getElementById('cu-id').value=String(user.id);document.getElementById('cu-nome').value=user.nm||'';document.getElementById('cu-usuario').value=user.usuario||'';document.getElementById('cu-matricula').value=user.matricula||'';document.getElementById('cu-email').value=user.email||'';const setor=sectors.find(item=>item.nome===user.setor);document.getElementById('cu-setor').value=setor?String(setor.id):'';document.getElementById('cu-perfil').value=user.perfil||'colaborador';populateUnitFilters();document.getElementById('cu-unit').value=user.unitId?String(user.unitId):String(currentUser?.unitId||'');document.getElementById('cu-submit').textContent='Salvar alteracoes';window.scrollTo({top:0,behavior:'smooth'});}
async function inactivateUser(id){const user=usersById[id];if(!user){toast('Usuario nao encontrado.','e');return;}if(!confirmAction(`Inativar o usuario ${user.nm}?`))return;try{const payload=await apiRequest('user-inactivate','POST',{id});ingestBootstrap(payload);renderUsersAdmin();if(currentUser?.id===id)doLogout();toast(`Usuario ${user.nm} inativado.`,'i');}catch(error){toast(error.message||'Falha ao inativar usuario.','e');}}
async function submitUnitCreate(event){event.preventDefault();if(!isNationalAdmin()){toast('Somente admin_nacional pode cadastrar unidades.','e');return;}const cidade=document.getElementById('unit-cidade').value.trim();const estado=document.getElementById('unit-estado').value.trim().toUpperCase();const codigo=document.getElementById('unit-codigo').value.trim().toUpperCase();if(!cidade||!estado||!codigo){toast('Preencha cidade, estado e codigo da unidade.','e');return;}if(!/^[A-Z]{2}$/.test(estado)){toast('Informe o estado com 2 letras (ex: PR).','e');return;}try{const payload=await apiRequest('unit-create','POST',{cidade,estado,codigo});ingestBootstrap(payload.bootstrap);populateUnitFilters();resetUnitCreateForm();toast(`Unidade ${payload.unit.nome} cadastrada com sucesso.`,'s');}catch(error){toast(error.message||'Falha ao cadastrar unidade.','e');}}
function resetUnitCreateForm(){['unit-cidade','unit-estado','unit-codigo'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});}
function renderUnitsAdmin(){const tbody=document.getElementById('tb-units');if(!tbody)return;const ordered=[...units].sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));tbody.innerHTML=!ordered.length?`<tr><td colspan="4">${emptyState('Nenhuma unidade cadastrada.',true)}</td></tr>`:ordered.map(unit=>`<tr><td>${escapeHtml(unit.nome)}</td><td>${escapeHtml(unit.cidade||'-')}</td><td>${escapeHtml(unit.estado||'-')}</td><td>${escapeHtml(unit.codigo||'-')}</td></tr>`).join('');}

function renderGalleryPublic(query=''){const container=document.getElementById('gal-pub');const filtered=query?models.filter(model=>model.nm.toLowerCase().includes(query.toLowerCase())||(model.desc||'').toLowerCase().includes(query.toLowerCase())):models;if(!filtered.length){container.innerHTML=emptyState('Nenhum modelo encontrado.');return;}container.innerHTML=filtered.map(model=>`<div class="gc"><div class="gi">${galleryImageMarkup(model.foto)}</div><div class="gb"><div class="gn">${escapeHtml(model.nm)}</div><div class="gd">${escapeHtml(model.desc||'Sem descricao cadastrada.')}</div><div class="gf"><div class="gw">~<b>${formatNumber(model.peso)}g</b></div><button class="btn bp bsm" type="button" onclick="openGalleryOrderModal(${model.id})">Solicitar</button></div></div></div>`).join('');}
function filtG(query){renderGalleryPublic(query);}function renderNewOrderContext(){if(!document.getElementById('np-fil').value&&filaments[0])document.getElementById('np-fil').value=String(filaments[0].id);}
function renderMyOrders(){const container=document.getElementById('my-list');const mine=orders.filter(order=>order.solicitanteId===currentUser?.id).sort((a,b)=>b.data.localeCompare(a.data));if(!mine.length){container.innerHTML=emptyState('Nenhum pedido encontrado. Solicite o primeiro na galeria.');return;}container.innerHTML=mine.map(order=>`<div class="mc"><div class="mct"><span class="mcid">PEDIDO #${order.id}</span><span class="badge ${statusClass(order.st)}">${escapeHtml(statusLabel(order.st))}</span></div><div class="mcm">${escapeHtml(order.mod)}</div><div class="mcmt"><span>${escapeHtml(order.fil)}</span><span>${escapeHtml(order.fin)}</span><span>${formatDate(order.data)}</span></div>${order.obs?`<div style="font-size:0.75rem;color:var(--tx2);margin-top:10px">Obs.: ${escapeHtml(order.obs)}</div>`:''}${order.dataLimite?`<div style="font-size:0.75rem;color:var(--tx2);margin-top:6px">Data limite: ${formatDate(order.dataLimite)}</div>`:''}${order.st==='Cancelado'?`<div class="al d" style="margin-top:14px;margin-bottom:0"><span>Este pedido foi cancelado.</span></div>`:renderSteps(order.st)}</div>`).join('');}
function renderSteps(status){const currentIndex=STEPS.indexOf(status);return `<div class="step-wrap">${STEPS.map((step,index)=>`${`<div class="step ${index<currentIndex?'done':index===currentIndex?'active':''}"><div class="step-c">${index<currentIndex?'&#10003;':index+1}</div><div class="step-lbl">${escapeHtml(statusLabel(step))}</div></div>`}${index<STEPS.length-1?`<div class="step-line ${index<currentIndex?'done':''}"></div>`:''}`).join('')}</div>`;}
function openFilModal(id=null){if(!isAdmin())return;editingFilamentId=id;document.getElementById('mf-title').textContent=id?'Editar Filamento':'Adicionar Filamento';document.getElementById('mf-save').textContent=id?'Atualizar':'Salvar';if(id){const filament=filaments.find(item=>item.id===id);if(!filament)return;document.getElementById('fi-cor').value=filament.cor;document.getElementById('fi-tipo').value=filament.tipo;document.getElementById('fi-peso').value=filament.peso;document.getElementById('fi-hex').value=filament.hex;}else clearFilamentForm();openM('mf');}
async function saveFil(){const cor=document.getElementById('fi-cor').value.trim();const tipo=document.getElementById('fi-tipo').value;const peso=Number.parseFloat(document.getElementById('fi-peso').value);const hex=normalizeHex(document.getElementById('fi-hex').value.trim()||'#888888');if(!cor||Number.isNaN(peso)||peso<0){toast('Preencha cor e peso com valores validos.','e');return;}try{await apiRequest('filament-save','POST',{id:editingFilamentId,cor,tipo,peso,hex});closeM('mf');clearFilamentForm();editingFilamentId=null;await loadBootstrap();renderStock();if(isAdmin())renderDashboard();toast('Filamento salvo com sucesso.','s');}catch(error){toast(error.message||'Falha ao salvar filamento.','e');}}
async function deleteFilament(id){if(!confirmAction('Remover este filamento?'))return;try{await apiRequest('filament-delete','POST',{id});await loadBootstrap();renderStock();if(isAdmin())renderDashboard();toast('Filamento removido.','i');}catch(error){toast(error.message||'Falha ao remover filamento.','e');}}
function openModModal(id=null){if(!isAdmin())return;editingModelId=id;document.getElementById('mm-title').textContent=id?'Editar Modelo':'Adicionar Modelo';document.getElementById('mm-save').textContent=id?'Atualizar':'Salvar';if(id){const model=models.find(item=>item.id===id);if(!model)return;document.getElementById('mo-nm').value=model.nm;document.getElementById('mo-desc').value=model.desc||'';document.getElementById('mo-peso').value=model.peso;document.getElementById('mo-link').value=model.link||'';const preview=document.getElementById('mo-prev');if(model.foto){preview.src=model.foto;preview.style.display='block';}else{preview.removeAttribute('src');preview.style.display='none';}}else clearModelForm();openM('mm');}
async function saveMod(){const nm=document.getElementById('mo-nm').value.trim();const desc=document.getElementById('mo-desc').value.trim();const peso=Number.parseFloat(document.getElementById('mo-peso').value)||0;const link=document.getElementById('mo-link').value.trim();const foto=document.getElementById('mo-prev').src||null;if(!nm){toast('Informe o nome do modelo.','e');return;}try{await apiRequest('model-save','POST',{id:editingModelId,nm,desc,peso,link,foto});closeM('mm');clearModelForm();editingModelId=null;await loadBootstrap();renderGalleryAdmin();renderGalleryPublic(document.getElementById('src-g')?.value||'');toast('Modelo salvo com sucesso.','s');}catch(error){toast(error.message||'Falha ao salvar modelo.','e');}}
async function deleteModel(id){if(!confirmAction('Remover este modelo?'))return;try{await apiRequest('model-delete','POST',{id});await loadBootstrap();renderGalleryAdmin();renderGalleryPublic(document.getElementById('src-g')?.value||'');toast('Modelo removido.','i');}catch(error){toast(error.message||'Falha ao remover modelo.','e');}}
function openStatusModal(id){if(!isAdmin()){toast('Somente administradores podem alterar status.','e');return;}const order=orders.find(item=>item.id===id);if(!order){toast('Pedido nao encontrado.','e');return;}editingStatusOrderId=id;document.getElementById('st-pid').textContent=`#${id} - ${order.mod}`;document.getElementById('st-sel').value=order.st;const model=models.find(item=>item.id===order.mId);const suggestedWeight=order.pesoGasto??(model?.peso||'');document.getElementById('st-peso').value=suggestedWeight!==''?String(suggestedWeight):'';toggleStatusWeightField();openM('ms');}
async function confirmSt(){const status=document.getElementById('st-sel').value;const rawWeight=document.getElementById('st-peso').value;const needsWeight=status==='Concluido'||status==='Retirado';const pesoGasto=rawWeight!==''?Number.parseFloat(rawWeight):null;if(needsWeight&&(pesoGasto===null||Number.isNaN(pesoGasto)||pesoGasto<=0)){toast('Informe a quantidade gasta para finalizar o pedido.','e');return;}try{await apiRequest('order-status','POST',{id:editingStatusOrderId,status,pesoGasto});closeM('ms');await loadBootstrap();renderDashboard();renderOrdersAdmin();renderStock();if(document.getElementById('sec-meus-pedidos').classList.contains('on'))renderMyOrders();toast(`Status atualizado para ${status}.`,'s');}catch(error){toast(error.message||'Falha ao atualizar status.','e');}}
function openGalleryOrderModal(modelId){if(!currentUser){toast('Entre no sistema para solicitar.','e');return;}const model=models.find(item=>item.id===modelId);if(!model){toast('Modelo nao encontrado.','e');return;}galleryOrderModelId=modelId;document.getElementById('gal-info').innerHTML=`<b>${escapeHtml(model.nm)}</b><br><span style="color:var(--tx2);font-size:0.77rem">${escapeHtml(model.desc||'Sem descricao')} · ~${formatNumber(model.peso)}g estimado</span>`;document.getElementById('gal-fil').value=filaments[0]?String(filaments[0].id):'';document.getElementById('gal-fin').value='';document.getElementById('gal-data').value='';openM('mp');}
async function pedirGal(){if(!galleryOrderModelId){toast('Selecione um modelo antes de solicitar.','e');return;}const model=models.find(item=>item.id===galleryOrderModelId);const filamentId=Number.parseInt(document.getElementById('gal-fil').value,10);const filament=filaments.find(item=>item.id===filamentId);const finalidade=document.getElementById('gal-fin').value.trim()||'Solicitacao via galeria';const dataLimite=document.getElementById('gal-data').value;if(!filament){toast('Selecione um filamento valido.','e');return;}if(dataLimite&&dataLimite<today()){toast('A data limite nao pode estar no passado.','e');return;}try{await apiRequest('order-create','POST',{solicitanteId:currentUser.id,mId:model?.id||null,fId:filament.id,fin:finalidade,dataLimite,obs:''});closeM('mp');galleryOrderModelId=null;await loadBootstrap();toast('Pedido enviado com sucesso.','s');go('meus-pedidos');}catch(error){toast(error.message||'Falha ao criar pedido.','e');}}
async function submitPed(){const modelId=Number.parseInt(document.getElementById('np-mod').value,10)||null;const filamentId=Number.parseInt(document.getElementById('np-fil').value,10);const finalidade=document.getElementById('np-fin').value.trim();const dataLimite=document.getElementById('np-data').value;const obs=document.getElementById('np-obs').value.trim();const img=document.getElementById('np-prev').src||null;if(!finalidade){toast('Informe a finalidade do pedido.','e');return;}if(dataLimite&&dataLimite<today()){toast('A data limite nao pode estar no passado.','e');return;}const filament=filaments.find(item=>item.id===filamentId);if(!filament){toast('Selecione um filamento valido.','e');return;}try{await apiRequest('order-create','POST',{solicitanteId:currentUser.id,mId:modelId,fId:filament.id,fin:finalidade,dataLimite,obs,img});resetNP();await loadBootstrap();toast('Pedido enviado com sucesso.','s');go('meus-pedidos');}catch(error){toast(error.message||'Falha ao criar pedido.','e');}}
function resetNP(){['np-fin','np-data','np-obs'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});document.getElementById('np-mod').value='';if(filaments[0])document.getElementById('np-fil').value=String(filaments[0].id);const input=document.getElementById('np-file');input.value='';const preview=document.getElementById('np-prev');preview.removeAttribute('src');preview.style.display='none';}
function clearFilamentForm(){['fi-cor','fi-peso','fi-hex'].forEach(id=>document.getElementById(id).value='');document.getElementById('fi-tipo').value='PLA';}
function clearModelForm(){['mo-nm','mo-desc','mo-peso','mo-link','mo-file'].forEach(id=>{const element=document.getElementById(id);if(element)element.value='';});const preview=document.getElementById('mo-prev');preview.removeAttribute('src');preview.style.display='none';}
function revokeSelectedProfilePhotoUrl(){if(selectedProfilePhotoUrl){URL.revokeObjectURL(selectedProfilePhotoUrl);selectedProfilePhotoUrl='';}}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=event=>resolve(String(event.target?.result||''));reader.onerror=()=>reject(new Error('Nao foi possivel ler a imagem selecionada.'));reader.readAsDataURL(file);});}
function prevImg(input,imageId){const file=input.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){toast('Selecione apenas imagens PNG ou JPG.','e');input.value='';return;}if(file.size>5*1024*1024){toast('A imagem deve ter no maximo 5MB.','e');input.value='';return;}const preview=document.getElementById(imageId);if(imageId==='photo-prev'){revokeSelectedProfilePhotoUrl();selectedProfilePhotoFile=file;selectedProfilePhotoUrl=URL.createObjectURL(file);preview.src=selectedProfilePhotoUrl;pendingProfilePhotoRemoval=false;syncProfilePhotoPreview();return;}const reader=new FileReader();reader.onload=event=>{preview.src=String(event.target?.result||'');preview.style.display='block';};reader.readAsDataURL(file);}
function openM(id){document.getElementById(id).classList.add('on');}
function closeM(id){document.getElementById(id).classList.remove('on');if(id==='mf'){editingFilamentId=null;clearFilamentForm();}if(id==='mm'){editingModelId=null;clearModelForm();}if(id==='mp')galleryOrderModelId=null;if(id==='mv')viewingOrderId=null;if(id==='mphoto'){const preview=document.getElementById('photo-prev');const input=document.getElementById('photo-file');pendingProfilePhotoRemoval=false;selectedProfilePhotoFile=null;revokeSelectedProfilePhotoUrl();if(preview){preview.removeAttribute('src');preview.style.display='none';}if(input)input.value='';syncProfilePhotoPreview();}if(id==='ms'){document.getElementById('st-peso').value='';toggleStatusWeightField();}}
async function apiRequest(action,method='GET',body=null,withAuth=true){const options={method,headers:{}};if(body){options.headers['Content-Type']='application/json';options.body=JSON.stringify(body);}if(withAuth&&getToken())options.headers.Authorization=`Bearer ${getToken()}`;const response=await fetch(`${API_URL}?action=${encodeURIComponent(action)}`,options);let payload={};try{payload=await response.json();}catch(error){throw new Error('Resposta invalida do servidor.');}if(response.status===401)clearToken();if(!response.ok||!payload.ok)throw new Error(payload.error||'Falha na comunicacao com o servidor.');return payload.data;}
function toast(message,type='i'){const icons={s:'<svg class="ti" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><polyline points="20 6 9 17 4 12"></polyline></svg>',e:'<svg class="ti" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><circle cx="12" cy="12" r="10"></circle><line x1="15" y1="9" x2="9" y2="15"></line><line x1="9" y1="9" x2="15" y2="15"></line></svg>',i:'<svg class="ti" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>'};const classes={s:'ts',e:'te',i:'ti2'};const element=document.createElement('div');element.className=`toast ${classes[type]||'ti2'}`;element.innerHTML=`${icons[type]||icons.i}<span>${escapeHtml(message)}</span>`;document.getElementById('tw2').appendChild(element);setTimeout(()=>{element.classList.add('out');setTimeout(()=>element.remove(),250);},3500);}
function statusClass(status){return{Pendente:'bpend','Em Producao':'bprod',Concluido:'bconc',Retirado:'bret',Cancelado:'bcan'}[status]||'bpend';}
function statusLabel(status){return{Pendente:'Pendente','Em Producao':'Em Produção',Concluido:'Concluído',Retirado:'Retirado',Cancelado:'Cancelado'}[status]||String(status||'');}
function priorityMarkup(priority){const label=priority>=10?'Alta':priority>=5?'Media':'Normal';const level=priority>=10?'alt':priority>=5?'med':'nor';return `<span class="pf ${level}"><span class="pfd"></span>${label}</span>`;}
function getFilamentColorToken(filament){const colorName=String(filament?.cor||'').trim().toLowerCase();const rawHex=String(filament?.hex||'').trim();const palette={vermelho:'#ff5a5f',azul:'#3b82f6',amarelo:'#facc15',branco:'#ffffff',preto:'#111827',verde:'#22c55e',laranja:'#fb923c',roxo:'#a855f7',rosa:'#f472b6',cinza:'#94a3b8',prata:'#cbd5e1',dourado:'#fbbf24',marrom:'#b45309',bege:'#d6b48a',transparente:'#dbeafe'};const validHex=/^#[0-9A-Fa-f]{6}$/.test(rawHex)&&rawHex.toLowerCase()!=='#888888';const background=validHex?rawHex:(palette[colorName]||'#94a3b8');const needsLightBorder=colorName==='branco'||background.toLowerCase()==='#ffffff';return{background,border:needsLightBorder?'1px solid #ddd':'2px solid rgba(255,255,255,0.85)'};}
function filamentHex(id){const filament=filaments.find(f=>f.id===id);return getFilamentColorToken(filament).background;}
function renderInstructorChart(){const container=document.getElementById('instr-chart');if(!container)return;const instructors=users.filter(user=>user.setor==='Instrutores');const rows=instructors.map(user=>({nm:user.nm,total:orders.filter(order=>order.solicitanteId===user.id).length})).sort((a,b)=>b.total-a.total||a.nm.localeCompare(b.nm,'pt-BR'));const max=Math.max(...rows.map(row=>row.total),1);if(!rows.length){container.innerHTML=emptyState('Nenhum instrutor cadastrado para exibir no grafico.');return;}container.innerHTML=rows.map(row=>`<div class="bar-row"><div class="bar-label">${escapeHtml(row.nm)}</div><div class="bar-track"><div class="bar-fill" style="width:${row.total/max*100}%"></div></div><div class="bar-value">${row.total}</div></div>`).join('');}
function openOrderViewModal(id){const order=orders.find(item=>item.id===id);if(!order){toast('Pedido nao encontrado.','e');return;}viewingOrderId=id;document.getElementById('ov-id').textContent=`Pedido #${order.id}`;document.getElementById('ov-modelo').textContent=order.mod;document.getElementById('ov-meta').innerHTML=`${detailLine('Solicitante',order.sol)}${detailLine('Setor',order.setor)}${detailLine('Filamento',order.fil)}${detailLine('Finalidade',order.fin||'-')}${detailLine('Data do pedido',formatDate(order.data))}${detailLine('Data limite',order.dataLimite?formatDate(order.dataLimite):'-')}${detailLine('Status',`<span class="badge ${statusClass(order.st)}">${escapeHtml(order.st)}</span>`,true)}${detailLine('Quantidade gasta',order.pesoGasto!==null?`${formatNumber(order.pesoGasto)}g`:'Nao informada')}${detailLine('Observacoes',order.obs||'-')}`;document.getElementById('ov-image').innerHTML=order.img?`<img src="${order.img}" alt="Imagem de referencia do pedido">`:'<div class="order-image-empty">Nenhuma imagem de referencia enviada.</div>';openM('mv');}
function focusOrderStatusFromView(){if(!viewingOrderId)return;closeM('mv');openStatusModal(viewingOrderId);}function toggleStatusWeightField(){const status=document.getElementById('st-sel').value;const wrap=document.getElementById('st-weight-wrap');if(!wrap)return;wrap.style.display=(status==='Concluido'||status==='Retirado')?'block':'none';}function detailLine(label,value,isHtml=false){return `<div class="od-row"><span>${escapeHtml(label)}</span><strong>${isHtml?value:escapeHtml(value)}</strong></div>`;}
function statusLabel(status){return{Pendente:'Pendente','Em Producao':'Em Produ\u00e7\u00e3o',Concluido:'Conclu\u00eddo',Retirado:'Retirado',Cancelado:'Cancelado'}[status]||String(status||'');}
function openOrderViewModal(id){const order=orders.find(item=>item.id===id);if(!order){toast('Pedido nao encontrado.','e');return;}viewingOrderId=id;document.getElementById('ov-id').textContent=`Pedido #${order.id}`;document.getElementById('ov-modelo').textContent=order.mod;document.getElementById('ov-meta').innerHTML=`${detailLine('Solicitante',order.sol)}${detailLine('Setor',order.setor)}${detailLine('Filamento',order.fil)}${detailLine('Finalidade',order.fin||'-')}${detailLine('Data do pedido',formatDate(order.data))}${detailLine('Data limite',order.dataLimite?formatDate(order.dataLimite):'-')}${detailLine('Status',`<span class="badge ${statusClass(order.st)}">${escapeHtml(statusLabel(order.st))}</span>`,true)}${detailLine('Quantidade gasta',order.pesoGasto!==null?`${formatNumber(order.pesoGasto)}g`:'Nao informada')}${detailLine('Observacoes',order.obs||'-')}`;document.getElementById('ov-image').innerHTML=order.img?`<img src="${order.img}" alt="Imagem de referencia do pedido">`:'<div class="order-image-empty">Nenhuma imagem de referencia enviada.</div>';openM('mv');}
function syncProfilePhotoPreview(){
  const preview=document.getElementById('photo-prev');
  const emptyState=document.getElementById('photo-empty-state');
  const clearButton=document.getElementById('photo-clear-btn');
  const previewWrap=document.getElementById('photo-preview-wrap');
  const hasPreview=Boolean(selectedProfilePhotoFile||preview?.src)&&!pendingProfilePhotoRemoval;
  if(preview)preview.style.display=hasPreview?'block':'none';
  if(emptyState)emptyState.style.display=hasPreview?'none':'flex';
  if(previewWrap)previewWrap.style.display=hasPreview?'flex':'none';
  if(clearButton)clearButton.style.display=hasPreview?'inline-flex':'none';
}
function clearProfilePhotoSelection(event){
  if(event)event.stopPropagation();
  const preview=document.getElementById('photo-prev');
  const input=document.getElementById('photo-file');
  if(input)input.value='';
  selectedProfilePhotoFile=null;
  revokeSelectedProfilePhotoUrl();
  if(preview){preview.removeAttribute('src');preview.style.display='none';}
  pendingProfilePhotoRemoval=Boolean(currentUser?.foto);
  syncProfilePhotoPreview();
}
function openProfilePhotoModal(){if(!currentUser){toast('Entre no sistema para alterar a foto.','e');return;}const preview=document.getElementById('photo-prev');const input=document.getElementById('photo-file');pendingProfilePhotoRemoval=false;selectedProfilePhotoFile=null;revokeSelectedProfilePhotoUrl();if(input)input.value='';if(currentUser.foto){preview.src=currentUser.foto;preview.style.display='block';}else{preview.removeAttribute('src');preview.style.display='none';}syncProfilePhotoPreview();openM('mphoto');}
async function saveProfilePhoto(){if(!currentUser){toast('Usuario nao encontrado.','e');return;}const removing=pendingProfilePhotoRemoval;let foto=null;if(selectedProfilePhotoFile){foto=await fileToDataUrl(selectedProfilePhotoFile);}if(!removing&&!foto){toast('Selecione uma nova imagem para salvar.','e');return;}try{await apiRequest('user-photo-save','POST',{id:currentUser.id,foto:removing?null:foto,remover:removing});closeM('mphoto');await loadBootstrap();setupSidebar();toast(removing?'Foto de perfil removida.':'Foto de perfil atualizada.','s');}catch(error){toast(error.message||'Falha ao salvar foto de perfil.','e');}}
function formatDate(dateString){if(!dateString)return'-';const [year,month,day]=dateString.split('-');return `${day}/${month}/${year}`;}function formatNumber(value){return Number(value).toLocaleString('pt-BR',{minimumFractionDigits:Number.isInteger(value)?0:1,maximumFractionDigits:1});}function formatWeight(value){const safeValue=Math.max(0,Number(value)||0);if(safeValue>=1000)return `${Number((safeValue/1000).toFixed(2)).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}kg`;return `${safeValue.toLocaleString('pt-BR',{maximumFractionDigits:0})}g`;}function formatConsumedRolls(value){const safeValue=Math.max(0,Number(value)||0);const label=safeValue===1?'bobina consumida':'bobinas consumidas';return `${Number(safeValue.toFixed(2)).toLocaleString('pt-BR',{minimumFractionDigits:safeValue%1===0?0:1,maximumFractionDigits:2})} ${label}`;}function today(){return new Date().toLocaleDateString('en-CA');}function daysBetween(from,to){return Math.floor((new Date(`${to}T00:00:00`)-new Date(`${from}T00:00:00`))/86400000);}function normalizeHex(value){return /^#[0-9A-Fa-f]{6}$/.test(value)?value:'#888888';}
function galleryImageMarkup(source){return source?`<img src="${source}" style="width:100%;height:100%;object-fit:cover" alt="Imagem do modelo">`:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="3" width="18" height="18" rx="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><path d="M21 15l-5-5L5 21"></path></svg>';}
function emptyState(message,compact=false){return `<div class="em"${compact?' style="padding:24px 12px"':''}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8"></path><path d="M14 2v6h6"></path></svg><p>${escapeHtml(message)}</p></div>`;}
function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
function confirmAction(message){return window.confirm(message);}







function isAdmin(){return['admin_local','admin_nacional'].includes(currentUser?.perfil);}
function isNationalAdmin(){return currentUser?.perfil==='admin_nacional';}
function syncSelectedUnit(){const stored=localStorage.getItem(UNIT_FILTER_KEY)||'';selectedUnitId=isNationalAdmin()&&stored&&units.some(unit=>String(unit.id)===stored)?stored:'';if(!isNationalAdmin())selectedUnitId='';}
function onUnitFilterChange(value){selectedUnitId=value||'';if(selectedUnitId)localStorage.setItem(UNIT_FILTER_KEY,selectedUnitId);else localStorage.removeItem(UNIT_FILTER_KEY);refreshAllSelects();if(document.getElementById('sec-dashboard')?.classList.contains('on'))renderDashboard();if(document.getElementById('sec-pedidos-admin')?.classList.contains('on'))renderOrdersAdmin();if(document.getElementById('sec-estoque')?.classList.contains('on'))renderStock();if(document.getElementById('sec-usuarios')?.classList.contains('on'))renderUsersAdmin();if(document.getElementById('sec-unidades')?.classList.contains('on'))renderUnitsAdmin();}
function applyUnitFilter(items){if(!isNationalAdmin()||!selectedUnitId)return items;return items.filter(item=>String(item.unitId)===String(selectedUnitId));}
function getVisibleOrders(){return applyUnitFilter(orders);}
function getVisibleFilaments(){return applyUnitFilter(filaments);}
function getVisibleHistory(){return applyUnitFilter(history);}
function getVisibleUsers(){return applyUnitFilter(users);}
function getVisibleFilamentStats(){if(!isNationalAdmin()||!selectedUnitId)return{registered:Number(filamentStats?.totals?.registered||0),active:Number(filamentStats?.totals?.active||0)};const unitStats=(filamentStats?.byUnit||[]).find(item=>String(item.unitId)===String(selectedUnitId));return{registered:Number(unitStats?.registered||0),active:Number(unitStats?.active||0)};}
function getVisibleConsumptionStats(){if(!isNationalAdmin()||!selectedUnitId)return{totalWeight:Number(consumptionStats?.totals?.totalWeight||0),rolls:Number(consumptionStats?.totals?.rolls||0)};const unitStats=(consumptionStats?.byUnit||[]).find(item=>String(item.unitId)===String(selectedUnitId));return{totalWeight:Number(unitStats?.totalWeight||0),rolls:Number(unitStats?.rolls||0)};}
function getAssignableUnits(){return isNationalAdmin()?units:units.filter(unit=>unit.id===currentUser?.unitId);}
function configureUserFormAccess(){const perfilSelect=document.getElementById('cu-perfil');if(!perfilSelect)return;const national=isNationalAdmin();perfilSelect.innerHTML=`<option value="colaborador">Colaborador</option><option value="admin_local">Administrador Local</option>${national?'<option value="admin_nacional">Administrador Nacional</option>':''}`;if(!national&&perfilSelect.value==='admin_nacional')perfilSelect.value='colaborador';}
function userRoleLabel(perfil){return{admin_local:'Administrador Local',admin_nacional:'Administrador Nacional',colaborador:'Colaborador'}[perfil]||'Colaborador';}











function buildUnitMetrics(){const currentMonth=today().slice(0,7);return units.map(unit=>{const unitOrders=orders.filter(order=>String(order.unitId)===String(unit.id));const completedOrders=unitOrders.filter(order=>['Concluido','Retirado'].includes(order.st));const monthOrders=completedOrders.filter(order=>(order.data||'').slice(0,7)===currentMonth);const printsMonth=monthOrders.length;const hoursMonth=Number((monthOrders.reduce((sum,order)=>sum+((Number(order.duracaoMinutos)||0)/60),0)).toFixed(2));const gramsMonth=monthOrders.reduce((sum,order)=>sum+(Number(order.pesoGasto)||0),0);const historyMonth=history.filter(item=>String(item.unitId)===String(unit.id)&&item.tipo==='Saida'&&(item.data||'').slice(0,7)===currentMonth);const historyGrams=historyMonth.reduce((sum,item)=>sum+(Number(item.qtd)||0),0);const totalGrams=gramsMonth>0?gramsMonth:historyGrams;return{unitId:unit.id,nome:unit.nome,printsMonth,hoursMonth,gramsMonth:totalGrams,rollsMonth:Number((totalGrams/1000).toFixed(2))};});}
function renderNationalDashboard(){const metrics=buildUnitMetrics();const selectedMetrics=selectedUnitId?metrics.filter(metric=>String(metric.unitId)===String(selectedUnitId)):metrics;const filamentRollSummary=getFilamentRollSummary(getVisibleFilaments());const totalPrints=selectedMetrics.reduce((sum,item)=>sum+item.printsMonth,0);const totalConsumption=getVisibleConsumptionStats();document.getElementById('stat-pedidos').textContent=String(totalPrints);document.getElementById('stat-pedidos-det').textContent='Total de Impressões';renderDashboardStockCard(filamentRollSummary,getVisibleFilaments());document.getElementById('stat-concluidos').textContent=formatWeight(totalConsumption.totalWeight);document.getElementById('stat-concluidos-det').textContent=formatConsumedRolls(totalConsumption.rolls);document.getElementById('stat-solicitantes').textContent=String(selectedMetrics.length);document.getElementById('stat-solicitantes-det').textContent='Unidades Ativas';renderPriorityQueuePreview();renderStatusDonut();renderInstructorChart();renderUnitMetricsChart();}
function renderUnitMetricsChart(){const container=document.getElementById('unit-metrics-chart');const subtitle=document.getElementById('unit-metrics-subtitle');if(!container)return;const metrics=buildUnitMetrics();const visibleMetrics=selectedUnitId?metrics.filter(metric=>String(metric.unitId)===String(selectedUnitId)):metrics;if(subtitle)subtitle.textContent=selectedUnitId?'Comparativo da unidade selecionada no mes atual':'Comparativo consolidado das unidades no mes atual';if(!visibleMetrics.length){container.innerHTML=emptyState('Nenhuma unidade encontrada para exibir no comparativo.');return;}const maxPrints=Math.max(...visibleMetrics.map(item=>item.printsMonth),1);const maxHours=Math.max(...visibleMetrics.map(item=>item.hoursMonth),1);const maxRolls=Math.max(...visibleMetrics.map(item=>item.rollsMonth),1);container.innerHTML=visibleMetrics.map(item=>`<div class="bar-group"><div class="bar-head"><div><strong>${escapeHtml(item.nome)}</strong></div><span>${item.printsMonth} impressões • ${formatNumber(item.rollsMonth)} rolos</span></div><div class="bar-row"><div class="bar-label">Impressões</div><div class="bar-track"><div class="bar-fill" style="width:${item.printsMonth/maxPrints*100}%"></div></div><div class="bar-value">${item.printsMonth}</div></div><div class="bar-row"><div class="bar-label">Horas</div><div class="bar-track"><div class="bar-fill" style="width:${item.hoursMonth/maxHours*100}%"></div></div><div class="bar-value">${formatNumber(item.hoursMonth)}h</div></div><div class="bar-row"><div class="bar-label">Rolos</div><div class="bar-track"><div class="bar-fill" style="width:${item.rollsMonth/maxRolls*100}%"></div></div><div class="bar-value">${formatNumber(item.rollsMonth)}</div></div></div>`).join('');}
